import type { Prestador, CategoriaOficio } from './types';

export const ZONAS = ['Pilar del Este', 'Pilar Centro', 'Nordelta', 'Tigre', 'Escobar'] as const;

export const CATEGORIAS_OFICIO: CategoriaOficio[] = [
  { slug: 'plomeria', nombre: 'Plomería', descripcion: 'Reparaciones, instalaciones y destapes de cañerías' },
  { slug: 'electricidad', nombre: 'Electricidad', descripcion: 'Instalaciones eléctricas, tableros y reparaciones' },
  { slug: 'gas-caldera', nombre: 'Gas y caldera', descripcion: 'Service de calderas, estufas y conexiones de gas' },
  { slug: 'aire-acondicionado', nombre: 'Aire acondicionado', descripcion: 'Instalación, limpieza y reparación de splits' },
  { slug: 'pintura', nombre: 'Pintura', descripcion: 'Pintura interior, exterior y tratamientos especiales' },
  { slug: 'albanileria', nombre: 'Albañilería', descripcion: 'Reformas, ampliaciones y trabajos de obra' },
  { slug: 'jardineria', nombre: 'Jardinería', descripcion: 'Mantenimiento de jardines, poda y parquización' },
  { slug: 'pileta', nombre: 'Pileta', descripcion: 'Limpieza, mantenimiento y reparación de piletas' },
  { slug: 'limpieza-tanque', nombre: 'Limpieza tanque', descripcion: 'Limpieza y desinfección de tanques de agua' },
  { slug: 'plagas', nombre: 'Plagas', descripcion: 'Fumigación y control de plagas domésticas' },
];

export const PRESTADORES_MOCK: Prestador[] = [
  {
    id: '1',
    nombre: 'Martín Fernández',
    iniciales: 'MF',
    avatarColor: '#1E3A5F',
    oficio: 'Plomero',
    categoria: 'plomeria',
    trabajos: 47,
    rating: 4.9,
    zonas: ['Pilar del Este', 'Escobar'],
    precioDesde: 25000,
    comparacionMercado: -12,
    badges: ['verificado', 'top'],
    sobreMi: 'Plomero matriculado con 15 años de experiencia en barrios privados de zona norte. Me especializo en reparaciones de pérdidas, cambio de cañerías y destapes complejos. Trabajo prolijo y limpio, siempre dejando todo en condiciones.',
    servicios: [
      { nombre: 'Reparación de pérdida', precio: '$25.000 - $45.000' },
      { nombre: 'Cambio de cañería', precio: '$80.000 - $150.000' },
      { nombre: 'Destape de desagüe', precio: '$18.000 - $35.000' },
      { nombre: 'Instalación de grifo', precio: '$15.000 - $25.000' },
    ],
    resenas: [
      { id: 'r1', autor: 'Ana García', iniciales: 'AG', fecha: '2026-03-20', texto: 'Excelente trabajo con la pérdida del baño. Vino puntual, resolvió rápido y dejó todo impecable.', rating: 5 },
      { id: 'r2', autor: 'Sergio Morales', iniciales: 'SM', fecha: '2026-03-05', texto: 'Muy buen plomero, conoce lo que hace. Me cambió toda la cañería del lavadero sin problemas.', rating: 5 },
      { id: 'r3', autor: 'Laura Rodríguez', iniciales: 'LR', fecha: '2026-02-18', texto: 'Puntual y profesional. Precio justo por el trabajo realizado.', rating: 4 },
      { id: 'r4', autor: 'Martín Guzmán', iniciales: 'MG', fecha: '2026-02-01', texto: 'Resolvió un problema que otros plomeros no pudieron. Muy recomendable.', rating: 5 },
      { id: 'r5', autor: 'Cecilia Paz', iniciales: 'CP', fecha: '2026-01-15', texto: 'Trabajo impecable. Ya lo llamé dos veces y siempre cumplió.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-03-15' },
      art: { activa: true, aseguradora: 'La Caja' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '2',
    nombre: 'Silvia Luna',
    iniciales: 'SL',
    avatarColor: '#2A9D8F',
    oficio: 'Plomera',
    categoria: 'plomeria',
    trabajos: 32,
    rating: 4.8,
    zonas: ['Nordelta', 'Tigre'],
    precioDesde: 22000,
    comparacionMercado: -18,
    badges: ['verificado', 'top'],
    sobreMi: 'Plomera matriculada especializada en reparaciones de urgencia y mantenimiento preventivo. Más de 10 años trabajando en countries y barrios cerrados de Nordelta y Tigre.',
    servicios: [
      { nombre: 'Reparación de pérdida', precio: '$22.000 - $40.000' },
      { nombre: 'Mantenimiento preventivo', precio: '$30.000 - $50.000' },
      { nombre: 'Instalación sanitaria', precio: '$60.000 - $120.000' },
    ],
    resenas: [
      { id: 'r6', autor: 'Pedro Álvarez', iniciales: 'PA', fecha: '2026-04-01', texto: 'Silvia es una genia. Resolvió todo en una hora y cobró lo justo.', rating: 5 },
      { id: 'r7', autor: 'Mariana Costa', iniciales: 'MC', fecha: '2026-03-22', texto: 'Muy profesional y atenta. Explicó cada paso del trabajo.', rating: 5 },
      { id: 'r8', autor: 'Javier Ruiz', iniciales: 'JR', fecha: '2026-03-10', texto: 'Excelente servicio, llegó a tiempo y trabajó muy prolijo.', rating: 5 },
      { id: 'r9', autor: 'Carla Benítez', iniciales: 'CB', fecha: '2026-02-28', texto: 'Recomendadísima. Le arregló la pérdida a mi vecina también.', rating: 4 },
      { id: 'r10', autor: 'Roberto Díaz', iniciales: 'RD', fecha: '2026-02-14', texto: 'Buen trabajo, puntual. El presupuesto coincidió con lo que cobró.', rating: 4 },
      { id: 'r11', autor: 'Natalia Vega', iniciales: 'NV', fecha: '2026-01-30', texto: 'Muy confiable. Ya es la plomera de referencia en nuestro barrio.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-02-20' },
      art: { activa: true, aseguradora: 'Provincia' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '3',
    nombre: 'Diego Romero',
    iniciales: 'DR',
    avatarColor: '#F4A261',
    oficio: 'Electricista',
    categoria: 'electricidad',
    trabajos: 63,
    rating: 4.9,
    zonas: ['Pilar del Este', 'Pilar Centro'],
    precioDesde: 20000,
    comparacionMercado: -8,
    badges: ['verificado', 'top'],
    sobreMi: 'Electricista matriculado con 20 años de experiencia. Especialista en tableros, tendido de líneas, automatización de portones y sistemas de iluminación para jardín.',
    servicios: [
      { nombre: 'Revisión de tablero', precio: '$20.000 - $35.000' },
      { nombre: 'Cambio de tendido eléctrico', precio: '$90.000 - $200.000' },
      { nombre: 'Instalación de luminarias', precio: '$15.000 - $40.000' },
      { nombre: 'Automatización de portón', precio: '$45.000 - $80.000' },
    ],
    resenas: [
      { id: 'r12', autor: 'Florencia Páez', iniciales: 'FP', fecha: '2026-04-10', texto: 'Diego es un crack. Me solucionó un cortocircuito que venía de años.', rating: 5 },
      { id: 'r13', autor: 'Tomás Herrera', iniciales: 'TH', fecha: '2026-03-25', texto: 'Muy detallista y prolijo. Dejó el tablero impecable.', rating: 5 },
      { id: 'r14', autor: 'Verónica Luna', iniciales: 'VL', fecha: '2026-03-12', texto: 'Excelente. Nos puso la iluminación del jardín y quedó espectacular.', rating: 5 },
      { id: 'r15', autor: 'Guillermo Soto', iniciales: 'GS', fecha: '2026-02-20', texto: 'Profesional serio y confiable. Precio acorde al trabajo.', rating: 4 },
      { id: 'r16', autor: 'Paula Méndez', iniciales: 'PM', fecha: '2026-02-05', texto: 'Resolvió rápido y explicó qué estaba fallando. Muy recomendable.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-01-10' },
      art: { activa: true, aseguradora: 'Federación Patronal' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '4',
    nombre: 'Carolina Méndez',
    iniciales: 'CM',
    avatarColor: '#E76F51',
    oficio: 'Electricista',
    categoria: 'electricidad',
    trabajos: 28,
    rating: 4.7,
    zonas: ['Nordelta', 'Escobar'],
    precioDesde: 22000,
    comparacionMercado: 0,
    badges: ['verificado'],
    sobreMi: 'Electricista matriculada con especialización en instalaciones domiciliarias y domótica básica. Trabajo en barrios privados de Nordelta y Escobar con puntualidad y compromiso.',
    servicios: [
      { nombre: 'Instalación de tomacorrientes', precio: '$22.000 - $38.000' },
      { nombre: 'Reparación eléctrica general', precio: '$25.000 - $55.000' },
      { nombre: 'Instalación de ventiladores de techo', precio: '$18.000 - $30.000' },
    ],
    resenas: [
      { id: 'r17', autor: 'Marcos Pereyra', iniciales: 'MP', fecha: '2026-04-05', texto: 'Muy buena. Instaló los ventiladores y quedaron perfectos.', rating: 5 },
      { id: 'r18', autor: 'Sandra López', iniciales: 'SL', fecha: '2026-03-18', texto: 'Puntual y profesional. Resolvió el problema del tablero rápido.', rating: 4 },
      { id: 'r19', autor: 'Lucas Ibarra', iniciales: 'LI', fecha: '2026-03-02', texto: 'Buen trabajo. Quizás un poco más cara que otros, pero confiable.', rating: 4 },
      { id: 'r20', autor: 'Daniela Ortiz', iniciales: 'DO', fecha: '2026-02-15', texto: 'Responsable y clara con el presupuesto. La recomiendo.', rating: 5 },
      { id: 'r21', autor: 'Ignacio Paz', iniciales: 'IP', fecha: '2026-01-28', texto: 'Excelente trabajo con la instalación eléctrica del quincho.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-02-01' },
      art: { activa: true, aseguradora: 'QBE Seguros' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '5',
    nombre: 'Pablo Iglesias',
    iniciales: 'PI',
    avatarColor: '#5A8DBF',
    oficio: 'Gasista',
    categoria: 'gas-caldera',
    trabajos: 55,
    rating: 4.8,
    zonas: ['Pilar del Este', 'Pilar Centro', 'Escobar'],
    precioDesde: 30000,
    comparacionMercado: -5,
    badges: ['verificado', 'top'],
    sobreMi: 'Gasista matriculado categoría 3ra con habilitación de MetroGAS. Especialista en service de calderas, calefones y estufas. Más de 18 años en la zona de Pilar.',
    servicios: [
      { nombre: 'Service de caldera', precio: '$30.000 - $50.000' },
      { nombre: 'Reparación de calefón', precio: '$25.000 - $45.000' },
      { nombre: 'Conexión de gas natural', precio: '$80.000 - $160.000' },
      { nombre: 'Service de estufa', precio: '$18.000 - $30.000' },
    ],
    resenas: [
      { id: 'r22', autor: 'Estela Vargas', iniciales: 'EV', fecha: '2026-04-08', texto: 'Pablo es muy profesional. Hizo el service de la caldera y quedó andando perfecto.', rating: 5 },
      { id: 'r23', autor: 'Ricardo Acuña', iniciales: 'RA', fecha: '2026-03-20', texto: 'Confío en Pablo para todo lo que sea gas. Muy cuidadoso y prolijo.', rating: 5 },
      { id: 'r24', autor: 'Mirta Giménez', iniciales: 'MG', fecha: '2026-03-05', texto: 'Nos instaló el calefón nuevo. Impecable el trabajo.', rating: 5 },
      { id: 'r25', autor: 'Andrés Blanc', iniciales: 'AB', fecha: '2026-02-18', texto: 'Cumplió con el horario y el presupuesto. Muy recomendable.', rating: 4 },
      { id: 'r26', autor: 'Graciela Torres', iniciales: 'GT', fecha: '2026-02-01', texto: 'Excelente gasista. Ya lo recomendé a varios vecinos.', rating: 5 },
      { id: 'r27', autor: 'Hugo Fernández', iniciales: 'HF', fecha: '2026-01-12', texto: 'Solucionó una fuga de gas que me tenía preocupado. Rápido y eficiente.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-01-20' },
      art: { activa: true, aseguradora: 'Sancor' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '6',
    nombre: 'Laura Acosta',
    iniciales: 'LA',
    avatarColor: '#2A9D8F',
    oficio: 'Técnica en climatización',
    categoria: 'aire-acondicionado',
    trabajos: 41,
    rating: 4.9,
    zonas: ['Nordelta', 'Tigre'],
    precioDesde: 18000,
    comparacionMercado: -10,
    badges: ['verificado', 'top'],
    sobreMi: 'Técnica en refrigeración y climatización. Me especializo en instalación, limpieza y reparación de equipos split de todas las marcas. Trabajo en zona norte con turno garantizado.',
    servicios: [
      { nombre: 'Limpieza de split', precio: '$18.000 - $28.000' },
      { nombre: 'Instalación de split', precio: '$45.000 - $75.000' },
      { nombre: 'Carga de gas refrigerante', precio: '$25.000 - $40.000' },
      { nombre: 'Reparación de split', precio: '$30.000 - $60.000' },
    ],
    resenas: [
      { id: 'r28', autor: 'Agustín Ramos', iniciales: 'AR', fecha: '2026-04-12', texto: 'Laura limpió los 4 splits de casa en una tarde. Impecable servicio.', rating: 5 },
      { id: 'r29', autor: 'Jimena Paz', iniciales: 'JP', fecha: '2026-03-28', texto: 'Instaló el split del dormitorio principal. Rapidísima y prolija.', rating: 5 },
      { id: 'r30', autor: 'Federico Sosa', iniciales: 'FS', fecha: '2026-03-15', texto: 'Muy recomendable. Sabe lo que hace y cobra razonable.', rating: 5 },
      { id: 'r31', autor: 'Claudia Pereyra', iniciales: 'CP', fecha: '2026-02-22', texto: 'Le cargó el gas al aire y ahora enfría como nuevo.', rating: 4 },
      { id: 'r32', autor: 'Diego Martínez', iniciales: 'DM', fecha: '2026-02-08', texto: 'Puntual, profesional. Ya la tengo agendada para el service anual.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-03-01' },
      art: { activa: true, aseguradora: 'La Caja' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '7',
    nombre: 'Ezequiel Sosa',
    iniciales: 'ES',
    avatarColor: '#1E3A5F',
    oficio: 'Pintor',
    categoria: 'pintura',
    trabajos: 89,
    rating: 5.0,
    zonas: ['Pilar del Este', 'Pilar Centro', 'Escobar'],
    precioDesde: 35000,
    comparacionMercado: 5,
    badges: ['verificado', 'top'],
    sobreMi: 'Pintor profesional con más de 20 años de oficio. Especialista en pintura de interiores y exteriores de alta gama. Trabajo con materiales premium y garantizo terminación impecable.',
    servicios: [
      { nombre: 'Pintura de habitación', precio: '$35.000 - $65.000' },
      { nombre: 'Pintura exterior completa', precio: '$150.000 - $350.000' },
      { nombre: 'Empapelado', precio: '$40.000 - $80.000' },
      { nombre: 'Tratamiento de humedad', precio: '$30.000 - $55.000' },
    ],
    resenas: [
      { id: 'r33', autor: 'Virginia Olmos', iniciales: 'VO', fecha: '2026-04-15', texto: 'Ezequiel es un artista. Pintó toda la casa y quedó espectacular.', rating: 5 },
      { id: 'r34', autor: 'Carlos Medina', iniciales: 'CM', fecha: '2026-04-01', texto: 'Impecable trabajo. Prolijo, limpio y cumplió los plazos.', rating: 5 },
      { id: 'r35', autor: 'Liliana Ríos', iniciales: 'LR', fecha: '2026-03-18', texto: 'Pintó el exterior bajo lluvia alternada y igual quedó perfecto.', rating: 5 },
      { id: 'r36', autor: 'Matías Bravo', iniciales: 'MB', fecha: '2026-03-02', texto: 'Excelente profesional. Un poco más caro pero vale cada peso.', rating: 5 },
      { id: 'r37', autor: 'Romina Agüero', iniciales: 'RA', fecha: '2026-02-12', texto: 'Trató la humedad del cuarto y ya no volvió. Genio.', rating: 5 },
      { id: 'r38', autor: 'Darío Leiva', iniciales: 'DL', fecha: '2026-01-25', texto: 'Lo recomiendo sin dudar. Trabaja con materiales de primera.', rating: 5 },
      { id: 'r39', autor: 'Susana Campos', iniciales: 'SC', fecha: '2026-01-10', texto: 'Ya lo contraté tres veces. Siempre cumple y el resultado es impecable.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-02-28' },
      art: { activa: true, aseguradora: 'Federación Patronal' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '8',
    nombre: 'Roberto Cabrera',
    iniciales: 'RC',
    avatarColor: '#E76F51',
    oficio: 'Albañil',
    categoria: 'albanileria',
    trabajos: 36,
    rating: 4.7,
    zonas: ['Pilar del Este', 'Escobar'],
    precioDesde: 40000,
    comparacionMercado: -7,
    badges: ['verificado'],
    sobreMi: 'Albañil con experiencia en reformas y ampliaciones. Trabajo con cuadrilla propia en barrios privados de zona norte. Presupuesto detallado y plazos claros.',
    servicios: [
      { nombre: 'Reforma de baño', precio: '$200.000 - $500.000' },
      { nombre: 'Construcción de parrilla', precio: '$150.000 - $350.000' },
      { nombre: 'Reparación de pared', precio: '$40.000 - $80.000' },
      { nombre: 'Construcción de deck', precio: '$120.000 - $250.000' },
    ],
    resenas: [
      { id: 'r40', autor: 'Néstor Gómez', iniciales: 'NG', fecha: '2026-04-02', texto: 'Roberto y su equipo nos reformaron el baño. Quedó hermoso.', rating: 5 },
      { id: 'r41', autor: 'Patricia Morel', iniciales: 'PM', fecha: '2026-03-15', texto: 'Buen trabajo con la parrilla. Tardó un poco más de lo esperado pero quedó bien.', rating: 4 },
      { id: 'r42', autor: 'Esteban López', iniciales: 'EL', fecha: '2026-02-28', texto: 'Profesional y honesto con los materiales. Recomendable.', rating: 4 },
      { id: 'r43', autor: 'Marina Quiroz', iniciales: 'MQ', fecha: '2026-02-10', texto: 'Reparó la pared de medianera. Buen acabado.', rating: 5 },
      { id: 'r44', autor: 'Alberto Sánchez', iniciales: 'AS', fecha: '2026-01-20', texto: 'Cumplió con el presupuesto y los plazos. Muy correcto.', rating: 4 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-01-15' },
      art: { activa: true, aseguradora: 'Provincia' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '9',
    nombre: 'María Pérez',
    iniciales: 'MP',
    avatarColor: '#5A8DBF',
    oficio: 'Jardinera',
    categoria: 'jardineria',
    trabajos: 72,
    rating: 4.8,
    zonas: ['Nordelta', 'Tigre', 'Escobar'],
    precioDesde: 15000,
    comparacionMercado: -15,
    badges: ['verificado', 'top'],
    sobreMi: 'Jardinera profesional con formación en paisajismo. Mantenimiento integral de jardines, poda de árboles, armado de canteros y sistema de riego. Trabajo en todo el GBA Norte.',
    servicios: [
      { nombre: 'Mantenimiento mensual', precio: '$15.000 - $30.000' },
      { nombre: 'Poda de árboles', precio: '$25.000 - $60.000' },
      { nombre: 'Armado de canteros', precio: '$20.000 - $45.000' },
      { nombre: 'Instalación de riego', precio: '$50.000 - $120.000' },
    ],
    resenas: [
      { id: 'r45', autor: 'Valeria Stein', iniciales: 'VS', fecha: '2026-04-10', texto: 'María es increíble. El jardín quedó como de revista.', rating: 5 },
      { id: 'r46', autor: 'Oscar Benítez', iniciales: 'OB', fecha: '2026-03-25', texto: 'Excelente servicio mensual. Siempre puntual y dedicada.', rating: 5 },
      { id: 'r47', autor: 'Lucía Mansilla', iniciales: 'LM', fecha: '2026-03-10', texto: 'Nos armó los canteros del frente. Hermosos.', rating: 5 },
      { id: 'r48', autor: 'Fernando Ruiz', iniciales: 'FR', fecha: '2026-02-20', texto: 'Podó los árboles que ya tocaban los cables. Rápida y eficiente.', rating: 4 },
      { id: 'r49', autor: 'Carolina Méndez', iniciales: 'CM', fecha: '2026-02-05', texto: 'Instaló el riego automático. Funciona perfecto.', rating: 5 },
      { id: 'r50', autor: 'Ramón Ocampo', iniciales: 'RO', fecha: '2026-01-18', texto: 'La mejor jardinera de la zona. La recomiendo siempre.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-03-10' },
      art: { activa: true, aseguradora: 'Sancor' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '10',
    nombre: 'Juan Carlos Vega',
    iniciales: 'JV',
    avatarColor: '#2A9D8F',
    oficio: 'Piletero',
    categoria: 'pileta',
    trabajos: 24,
    rating: 4.6,
    zonas: ['Pilar del Este', 'Pilar Centro'],
    precioDesde: 20000,
    comparacionMercado: 3,
    badges: ['verificado'],
    sobreMi: 'Especialista en mantenimiento y reparación de piletas. Tratamiento del agua, reparación de bombas y filtros, y preparación para temporada. Más de 12 años en la zona de Pilar.',
    servicios: [
      { nombre: 'Limpieza de pileta', precio: '$20.000 - $35.000' },
      { nombre: 'Reparación de bomba', precio: '$35.000 - $70.000' },
      { nombre: 'Preparación para verano', precio: '$30.000 - $55.000' },
      { nombre: 'Reparación de venecitas', precio: '$50.000 - $100.000' },
    ],
    resenas: [
      { id: 'r51', autor: 'Elena Castillo', iniciales: 'EC', fecha: '2026-04-05', texto: 'Juan Carlos preparó la pileta para el verano. Agua cristalina.', rating: 5 },
      { id: 'r52', autor: 'Gustavo Paez', iniciales: 'GP', fecha: '2026-03-20', texto: 'Reparó la bomba que no andaba. Buen servicio.', rating: 4 },
      { id: 'r53', autor: 'Mercedes Villa', iniciales: 'MV', fecha: '2026-03-05', texto: 'Arregló las venecitas que se habían despegado. Bien.', rating: 4 },
      { id: 'r54', autor: 'Alejandro Duarte', iniciales: 'AD', fecha: '2026-02-15', texto: 'Cumplidor y honesto. Precio razonable.', rating: 5 },
      { id: 'r55', autor: 'Inés Barreto', iniciales: 'IB', fecha: '2026-01-28', texto: 'Viene todos los meses a mantener la pileta. Muy bien.', rating: 4 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-02-10' },
      art: { activa: true, aseguradora: 'QBE Seguros' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '11',
    nombre: 'Andrés Quiroga',
    iniciales: 'AQ',
    avatarColor: '#F4A261',
    oficio: 'Especialista en tanques',
    categoria: 'limpieza-tanque',
    trabajos: 18,
    rating: 4.5,
    zonas: ['Pilar del Este', 'Nordelta', 'Escobar'],
    precioDesde: 25000,
    comparacionMercado: 0,
    badges: ['verificado'],
    sobreMi: 'Me dedico a la limpieza y desinfección de tanques de agua domiciliarios. Trabajo con productos habilitados y emito certificado de limpieza. Cubro todo el GBA Norte.',
    servicios: [
      { nombre: 'Limpieza de tanque 500L', precio: '$25.000 - $35.000' },
      { nombre: 'Limpieza de tanque 1000L', precio: '$35.000 - $50.000' },
      { nombre: 'Limpieza de cisterna', precio: '$40.000 - $65.000' },
    ],
    resenas: [
      { id: 'r56', autor: 'Marta Villalba', iniciales: 'MV', fecha: '2026-03-28', texto: 'Limpió el tanque y la cisterna. Dejó todo impecable con certificado.', rating: 5 },
      { id: 'r57', autor: 'Raúl Giménez', iniciales: 'RG', fecha: '2026-03-10', texto: 'Buen servicio. Puntual y rápido.', rating: 4 },
      { id: 'r58', autor: 'Soledad Arce', iniciales: 'SA', fecha: '2026-02-20', texto: 'Cumplió con lo pactado. Recomendable.', rating: 4 },
      { id: 'r59', autor: 'Hernán Costa', iniciales: 'HC', fecha: '2026-02-01', texto: 'Profesional y prolijo. Emitió el certificado en el momento.', rating: 5 },
      { id: 'r60', autor: 'Laura Rivas', iniciales: 'LR', fecha: '2026-01-15', texto: 'Lo contratamos para todo el consorcio. Excelente.', rating: 5 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-01-25' },
      art: { activa: true, aseguradora: 'La Caja' },
      dniCuit: true,
      referencias: true,
    },
  },
  {
    id: '12',
    nombre: 'Patricia Fernández',
    iniciales: 'PF',
    avatarColor: '#1E3A5F',
    oficio: 'Fumigadora',
    categoria: 'plagas',
    trabajos: 34,
    rating: 4.7,
    zonas: ['Pilar del Este', 'Pilar Centro', 'Tigre'],
    precioDesde: 20000,
    comparacionMercado: -6,
    badges: ['verificado'],
    sobreMi: 'Fumigadora matriculada con experiencia en control de plagas urbanas. Trabajo con productos aprobados por SENASA, aptos para familias con chicos y mascotas. Servicio integral en barrios privados.',
    servicios: [
      { nombre: 'Fumigación general (cucarachas, hormigas)', precio: '$20.000 - $35.000' },
      { nombre: 'Control de roedores', precio: '$25.000 - $45.000' },
      { nombre: 'Fumigación de jardín (mosquitos)', precio: '$18.000 - $30.000' },
      { nombre: 'Tratamiento de termitas', precio: '$40.000 - $80.000' },
    ],
    resenas: [
      { id: 'r61', autor: 'Beatriz Navarro', iniciales: 'BN', fecha: '2026-04-08', texto: 'Patricia fumigó toda la casa. No volvimos a ver una cucaracha.', rating: 5 },
      { id: 'r62', autor: 'Cristian Molina', iniciales: 'CM', fecha: '2026-03-22', texto: 'Muy profesional. Usó productos seguros para los chicos.', rating: 5 },
      { id: 'r63', autor: 'Rosa Santana', iniciales: 'RS', fecha: '2026-03-08', texto: 'Fumigó el jardín y se acabaron los mosquitos. Genial.', rating: 5 },
      { id: 'r64', autor: 'Emilio Vargas', iniciales: 'EV', fecha: '2026-02-18', texto: 'Buen servicio de control de roedores. Cumplió.', rating: 4 },
      { id: 'r65', autor: 'Adriana Paz', iniciales: 'AP', fecha: '2026-02-01', texto: 'La contratamos por el consorcio del barrio. Excelente resultado.', rating: 5 },
      { id: 'r66', autor: 'Jorge Ríos', iniciales: 'JR', fecha: '2026-01-12', texto: 'Muy clara con las instrucciones post-fumigación. Profesional.', rating: 4 },
    ],
    documentacion: {
      antecedentes: { verificado: true, fecha: '2026-02-15' },
      art: { activa: true, aseguradora: 'Provincia' },
      dniCuit: true,
      referencias: true,
    },
  },
];
